export const SELECT_FROM_CATALOG = "SELECT_FROM_CATALOG";
export const DELETE_FROM_SELECTED = "DELETE_FROM_SELECTED";
export const CHANGE_ACCESS_RIGHTS = "CHANGE_ACCESS_RIGHTS";
export const DELETE_FROM_CATALOG = "DELETE_FROM_CATALOG";
